version: "3.3"
services:
        proxy:
                        image: jwilder/nginx-proxy:alpine
                        container_name: nextcloud-proxy
                        networks:
                                - nextcloud_network
                        ports:
                                - "81:80"
                                - "433:443"
                        volumes:
                                - ./proxy/conf.d:/etc/nginx/conf.d:rw
                                - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
                                - ./proxy/html:/usr/share/nginx/html:rw
                                - ./proxy/certs:/etc/nginx/certs:ro
                                - /etc/localtime:/etc/localtime:ro
                                - /var/run/docker.sock:/tmp/docker.sock:ro
                        restart: unless-stopped


        letsencrypt:
                        image: jrcs/letsencrypt-nginx-proxy-companion
                        container_name: nextcloud-letsencrypt
                        networks:
                              - nextcloud_network
                        depends_on: 
                                - proxy
                        environment:
                                - NGINX_PROXY_CONTAINER=nextcloud-proxy
                        volumes:
                                - ./proxy/certs:/etc/nginx/certs:rw
                                - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
                                - ./proxy/html:/usr/share/nginx/html:rw
                                - /etc/localtime:/etc/localtime:ro
                                - /var/run/docker.sock:/var/run/docker.sock:ro
                        restart: unless-stopped
        db:

                        image: mariadb
                        container_name: nextcloud-mariadb
                        networks:
                               - nextcloud_network
                        volumes:
                                - db:/var/lib/mysql
                                - /etc/localtime:/etc/localtime:ro
                        environment:
                                -  MYSQL_ROOT_PASSWORD=123
                                -  MYSQL_PASSWORD=456
                                -  MYSQL_DATABASE=nextcloud
                                -  MYSQL-USER=nextcloud
                        restart: unless-stopped
        
        app:
                        image: nextcloud:latest
                        container_name: nextcloud-app
                        depends_on:
                                - proxy
                                - letsencrypt
                                - db

                        networks:
                                  - nextcloud_network
                        volumes:
                                - nextcloud:/var/lib/www/html
                                - ./app/config:/var/www/html/config
                                - ./app/custom_apps:/var/www/html/custom_apps
                                - ./app/data/:/var/www/html/data
                                - ./app/themes:/var/www/html/themes
                                - /etc/localtime:/etc/localtime:ro
                        environment:
                                - VIRTUAL_HOST=192.168.56.104
                                - LETSENCRYPT_HOST=192.168.56.104
                                - LETSENCRYPT_EMAIL=alirezahamzeh7010@gmail.com
                        restart: unless-stopped

volumes:
        nextcloud: {}
        db: {} 
networks:
        nextcloud_network:
